#------------------------------------------------------------------------------
#
#  $Id: Kbuild 790 2007-02-21 12:41:25Z fp $
#
#  Copyright (C) 2006  Florian Pose, Ingenieurgemeinschaft IgH
#
#  This file is part of the IgH EtherCAT Master.
#
#  The IgH EtherCAT Master is free software; you can redistribute it
#  and/or modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  The IgH EtherCAT Master is distributed in the hope that it will be
#  useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with the IgH EtherCAT Master; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#  The right to use EtherCAT Technology is granted and comes free of
#  charge under condition of compatibility of product made by
#  Licensee. People intending to distribute/sell products based on the
#  code, have to sign an agreement to guarantee that products using
#  software based on IgH EtherCAT master stay compatible with the actual
#  EtherCAT specification (which are released themselves as an open
#  standard) as the (only) precondition to have the right to use EtherCAT
#  Technology, IP and trade marks.
#
#------------------------------------------------------------------------------

TOPDIR := $(src)/../..
include $(TOPDIR)/config.kbuild

REV := $(shell if test -s $(TOPDIR)/svnrevision; then \
		cat $(TOPDIR)/svnrevision; \
	else \
		svnversion $(TOPDIR) 2>/dev/null || echo "unknown"; \
	fi)

ifeq ($(EC_ENABLE_E1000),1)
	EC_E1000_OBJ := e1000_main-$(EC_E1000_KERNEL)-ethercat.o \
        e1000_hw-$(EC_E1000_KERNEL)-ethercat.o \
        e1000_ethtool-$(EC_E1000_KERNEL)-ethercat.o \
        e1000_param-$(EC_E1000_KERNEL)-ethercat.o
	obj-m += ec_e1000.o
	ec_e1000-objs := $(EC_E1000_OBJ)
	CFLAGS_e1000_main-$(EC_E1000_KERNEL)-ethercat.o = -DSVNREV=$(REV)
endif

#------------------------------------------------------------------------------
